"use client";
import Header from "@/components/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import { Provider } from "react-redux";
import { store } from "./../context/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <Provider store={store}>
          <body className={inter.className}>
            <Header />
            {children}
          </body>
        </Provider>
      </html>
    </>
  );
}
